# Generated by Django 3.1.13 on 2021-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auditionpic/')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('role_interested', models.TextField()),
                ('list_any_talent_or_performing_experience', models.TextField()),
                ('do_you_have_any_physical_limitation', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
