# Generated by Django 3.1.13 on 2021-12-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='parents_email',
            field=models.CharField(default='got@go.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='parents_name',
            field=models.CharField(default='David Eze', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='parents_phone_number',
            field=models.IntegerField(default=19035089576),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='state',
            field=models.CharField(default='Enugu', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='will_you_consider_being_an_extra',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='will_you_consider_other_roles',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='will_you_help_with_production',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
