# Generated by Django 3.1.13 on 2021-12-04 20:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211204_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='parents_phone_number',
            field=phone_field.models.PhoneField(help_text='Parent Phone Number', max_length=31),
        ),
        migrations.AlterField(
            model_name='audit',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Your Phone Number', max_length=31),
        ),
    ]
