# Generated by Django 3.1.13 on 2021-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211205_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
    ]
